### ISSUE TITLE
Even a 11kb image uploaded to Colab causes Cuda out of memory

### ISSUE THREAD

**Issue by chenxwh** [SenHe/DLFS#1]
Hi I am trying out your model cool on colab, but even a 11kb 256*256 image uploaded will cause cuda out of memory? same happens to my 16G RAM GPU. I wonder whether that is to be expected - can you provide example images that can run on colab?

**Comment by zhangzhili1112** [comment]
Hi, are you also debugging this code, and can you successfully download the dataset please?

**Comment by SenHe** [comment]
> Hi I am trying out your model cool on colab, but even a 11kb 256*256 image uploaded will cause cuda out of memory? same happens to my 16G RAM GPU. I wonder whether that is to be expected - can you provide example images that can run on colab?

Hi, 
Sorry for the late reply.
I'm not sure if it is because some colab settings have been changed. 
I can run the demo on colab previously. But now I got the same error. In this case, I would suggest you to download the model and run it locally.
