### ISSUE TITLE
How to get the metric of paper?

### ISSUE THREAD

**Issue by zwy1996** [SenHe/DLFS#2]
Hi,

Thanks for you nice work. When I used your code to test on the test dataset, I only got the some images, but I could not get the age error, reconfiguration and so on. 

Should I use other progarm? or other methods, Could you give me some suggestions?

Best wishes to you!

**Comment by SenHe** [comment]
Thanks for your interest in our work.

For the evaluation, please refer to the 3rd paragraph in the experiment section.

**Comment by zwy1996** [comment]
Thank you for your reponse in time!

I get it!
